-- Create the database (if not already existing)
CREATE DATABASE user_authentication;

-- Use the database
USE user_authentication;

-- Create the users table
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Example: Inserting a user (hashed password should be generated by your application)
-- Replace 'hashed_password_here' with an actual hashed password
INSERT INTO users (username, password_hash) VALUES ('example_user', 'hashed_password_here');
